// AUTO-GENERATED by sweep — edit layout.json then run: sweep generate
#pragma once

// Tapping term — start at 200ms, tune ±25ms if HRMs misfire / feel sluggish
#define TAPPING_TERM 200

// Zero QUICK_TAP disables double-tap auto-repeat (prevents "aaaa" HRM misfires)
#define QUICK_TAP_TERM 0

// Combo detection window
#define COMBO_TERM 50

// DO NOT enable HOLD_ON_OTHER_KEY_PRESS — destroys HRM usability
// DO NOT enable PERMISSIVE_HOLD globally — causes misfires on key rolls
