// AUTO-GENERATED by sweep — edit layout.json then run: sweep generate
#pragma once

// Tapping term — start at 200ms, tune ±25ms if HRMs misfire / feel sluggish
#define TAPPING_TERM 200

// Zero QUICK_TAP disables double-tap auto-repeat (prevents "aaaa" HRM misfires)
#define QUICK_TAP_TERM 0

// Combo detection window
#define COMBO_TERM 50

// VIA support: allow all 6 layers
#define DYNAMIC_KEYMAP_LAYER_COUNT 6

// DO NOT enable HOLD_ON_OTHER_KEY_PRESS — destroys HRM usability
// DO NOT enable PERMISSIVE_HOLD globally — causes misfires on key rolls

// Split serial pin for the GP0 rewire
#define SERIAL_USART_TX_PIN GP0
