// AUTO-GENERATED by sweep — edit layout.json then run: sweep generate
#include QMK_KEYBOARD_H
#include "users/holykeebs/holykeebs.h"

// --- Layer indices --------------------------------------------------
enum layers {
    BASE,
    NAV,
    SYM,
    NUM,
    MOUSE,
    SYSTEM,
};

// --- Combos ---------------------------------------------------------
const uint16_t PROGMEM jk_esc[] = {RSFT_T(KC_J), RCTL_T(KC_K), COMBO_END};
const uint16_t PROGMEM inner_thumbs_system[] = {LT(NAV,KC_BSPC), LT(SYM,KC_SPC), COMBO_END};
const uint16_t PROGMEM zslash_capsword[] = {KC_Z, KC_SLSH, COMBO_END};

combo_t key_combos[] = {
    COMBO(jk_esc, KC_ESC),  // N+E in Colemak (right home index+middle) -> Escape for Vim
    COMBO(inner_thumbs_system, MO(SYSTEM)),  // Both inner thumbs -> system/boot layer
    COMBO(zslash_capsword, CW_TOGG),  // Z+/ (bottom row outer columns) -> Caps Word for CONSTANT_CASE
};

// --- Keymaps --------------------------------------------------------
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

[BASE] = LAYOUT_split_3x5_2(
    KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P,
    LGUI_T(KC_A), LALT_T(KC_S), LCTL_T(KC_D), LSFT_T(KC_F), KC_G, KC_H, RSFT_T(KC_J), RCTL_T(KC_K), RALT_T(KC_L), RGUI_T(KC_SCLN),
    KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH,
    LT(MOUSE,KC_TAB), LT(NAV,KC_BSPC), LT(SYM,KC_SPC), LT(NUM,KC_ENT)
),

[NAV] = LAYOUT_split_3x5_2(
    KC_ESC, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_HOME, KC_PGDN, KC_PGUP, KC_END,
    KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, XXXXXXX, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_INS,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX, _______, KC_ENT, KC_DEL
),

[SYM] = LAYOUT_split_3x5_2(
    KC_LCBR, KC_AMPR, KC_ASTR, KC_LPRN, KC_RCBR, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    S(KC_P), KC_DLR, KC_PERC, KC_CIRC, KC_PLUS, XXXXXXX, KC_RSFT, KC_RCTL, KC_RALT, KC_RGUI,
    KC_TILD, KC_EXLM, KC_AT, KC_HASH, KC_PIPE, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    KC_QUOT, KC_RPRN, _______, KC_UNDS
),

[NUM] = LAYOUT_split_3x5_2(
    KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_LBRC, KC_7, KC_8, KC_9, KC_RBRC,
    KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_F11, KC_SCLN, KC_4, KC_5, KC_6, KC_EQL,
    KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_GRV, KC_1, KC_2, KC_3, KC_BSLS,
    KC_F12, KC_0, KC_MINS, _______
),

[MOUSE] = LAYOUT_split_3x5_2(
    QK_BOOT, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, QK_BOOT,
    KC_LGUI, HK_D_MODE, MS_BTN2, MS_BTN1, MS_BTN3, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    _______, MS_BTN1, XXXXXXX, XXXXXXX
),

[SYSTEM] = LAYOUT_split_3x5_2(
    QK_BOOT, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, QK_BOOT,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX, _______, _______, XXXXXXX
),

};

// --- Per-key tapping term -------------------------------------------
uint16_t get_tapping_term(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case LGUI_T(KC_A):  // pinky — slowest
        case RGUI_T(KC_SCLN):  // pinky — slowest
            return TAPPING_TERM + 30;  // 230ms
        case LALT_T(KC_S):  // ring — slow
        case RALT_T(KC_L):  // ring — slow
            return TAPPING_TERM + 15;  // 215ms
        case LSFT_T(KC_F):  // index — fastest
        case RSFT_T(KC_J):  // index — fastest
            return TAPPING_TERM - 20;  // 180ms
        default:
            return TAPPING_TERM;
    }
}
