// AUTO-GENERATED by sweep — edit layout.json then run: sweep generate
#include QMK_KEYBOARD_H

// ─── Layer indices ──────────────────────────────────────────────────
enum layers {
    BASE,
    NAV,
    SYM,
    NUM,
    MED,
};

// ─── Combos ─────────────────────────────────────────────────────────
const uint16_t PROGMEM jk_esc[] = {KC_J, KC_K, COMBO_END};
const uint16_t PROGMEM nm_coln[] = {RSFT_T(KC_N), KC_M, COMBO_END};
const uint16_t PROGMEM ui_del[] = {KC_U, KC_I, COMBO_END};
const uint16_t PROGMEM lq_capsword[] = {KC_L, KC_QUOT, COMBO_END};
const uint16_t PROGMEM df_tab[] = {KC_D, KC_F, COMBO_END};

combo_t key_combos[] = {
    COMBO(jk_esc, KC_ESC),  // jk → Escape (Neovim muscle memory)
    COMBO(nm_coln, KC_COLN),  // nm → Colon (fast Neovim command mode)
    COMBO(ui_del, KC_DEL),  // ui → Delete
    COMBO(lq_capsword, CW_TOGG),  // l' → Caps Word toggle (smarter than Caps Lock)
    COMBO(df_tab, KC_TAB),  // df → Tab (left hand only, useful in terminal)
};

// ─── Key overrides ──────────────────────────────────────────────────
const key_override_t kc_comm_ko = ko_make_basic(MOD_MASK_SHIFT, KC_COMM, KC_SCLN);  // Shift+, → ; (recover semicolon)
const key_override_t kc_dot_ko = ko_make_basic(MOD_MASK_SHIFT, KC_DOT, KC_COLN);  // Shift+. → : (recover colon, alternative to combo)

const key_override_t *key_overrides[] = {
    &kc_comm_ko,
    &kc_dot_ko,
    NULL
};

// ─── Keymaps ────────────────────────────────────────────────────────
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

[BASE] = LAYOUT_split_3x5_2(
    KC_Q, KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_QUOT,
    LGUI_T(KC_A), LALT_T(KC_R), LCTL_T(KC_S), LSFT_T(KC_T), KC_G, KC_M, RSFT_T(KC_N), RCTL_T(KC_E), LALT_T(KC_I), RGUI_T(KC_O),
    KC_Z, KC_X, KC_C, KC_D, KC_V, KC_K, KC_H, KC_COMM, KC_DOT, KC_SLSH,
    LT(MED,KC_TAB), LT(NAV,KC_SPC), LT(SYM,KC_ENT), LT(NUM,KC_BSPC)
),

[NAV] = LAYOUT_split_3x5_2(
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_PGUP, KC_HOME, KC_UP, KC_END, KC_DEL,
    KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, XXXXXXX, KC_PGDN, KC_LEFT, KC_DOWN, KC_RGHT, KC_BSPC,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_INS, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    _______, _______, KC_ENT, _______
),

[SYM] = LAYOUT_split_3x5_2(
    KC_ESC, KC_LBRC, KC_LCBR, KC_LPRN, KC_TILD, KC_CIRC, KC_RPRN, KC_RCBR, KC_RBRC, KC_GRV,
    KC_MINS, KC_ASTR, KC_EQL, KC_UNDS, KC_DLR, KC_HASH, KC_EXLM, KC_AT, KC_SLSH, KC_QUES,
    KC_PLUS, KC_PIPE, KC_LT, KC_GT, KC_PERC, KC_BSLS, KC_AMPR, KC_SCLN, KC_COLN, KC_DQUO,
    _______, KC_SPC, _______, _______
),

[NUM] = LAYOUT_split_3x5_2(
    KC_7, KC_5, KC_3, KC_1, KC_9, KC_8, KC_0, KC_2, KC_4, KC_6,
    KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_F11, KC_F10, KC_RSFT, KC_RCTL, KC_LALT, KC_RGUI,
    KC_F7, KC_F5, KC_F3, KC_F1, KC_F9, KC_F8, KC_F12, KC_F2, KC_F4, KC_F6,
    _______, _______, _______, _______
),

[MED] = LAYOUT_split_3x5_2(
    QK_BOOT, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, RGB_TOG, RGB_MOD, RGB_HUI, RGB_SAI, RGB_VAI,
    XXXXXXX, KC_MPRV, KC_VOLD, KC_VOLU, KC_MNXT, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    _______, KC_MPLY, KC_MSTP, KC_MUTE
),

};

// ─── Per-key tapping term ───────────────────────────────────────────
uint16_t get_tapping_term(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case LGUI_T(KC_A):  // pinky — slower
        case RGUI_T(KC_O):  // pinky — slower
            return TAPPING_TERM + 50;  // 250ms
        case LSFT_T(KC_T):  // index — faster
        case RSFT_T(KC_N):  // index — faster
            return TAPPING_TERM - 20;  // 180ms
        default:
            return TAPPING_TERM;
    }
}
