# AUTO-GENERATED by sweep — edit layout.json then run: sweep generate

COMBO_ENABLE        = yes
CAPS_WORD_ENABLE    = yes
TRI_LAYER_ENABLE    = yes   # hold NAV + SYM simultaneously → NUM layer
KEY_OVERRIDE_ENABLE = yes

# Optional — enable if needed:
# TAP_DANCE_ENABLE  = yes   # adds tapping_term latency per key — avoid unless needed
# MOUSEKEY_ENABLE   = yes
