# AUTO-GENERATED by sweep — edit layout.json then run: sweep generate

COMBO_ENABLE        = yes
CAPS_WORD_ENABLE    = yes
VIA_ENABLE          = yes
MOUSEKEY_ENABLE     = yes

# Optional — enable if needed:
# TAP_DANCE_ENABLE  = yes   # adds tapping_term latency per key — avoid unless needed
